# Generated by Django 4.0.2 on 2022-03-02 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_fim_pagamento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
